from tensorflow/tensorflow:latest-gpu-jupyter

WORKDIR /home/big_data_analytics_extension_course/

RUN pip install --upgrade pip

# the image already comes with tensorflow and matplotlib
RUN pip install scikit-learn pandas
